version: '2.4'
services: 
  express-app: 
    container_name: 'warbler-api'
    image: 'jchengdeveng/warbler-api-dev'
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
      args:
        BUILD_DATE: '$BUILD_DATE'
        SOURCE_COMMIT: '$COMMIT'
    ports: 
      - 8081:8081 
    volumes: 
      - .:/node/app
      - /node/node_modules 
    env_file:
      - ./.env
